### ISSUE TITLE
Add color to Card

### ISSUE THREAD

**Issue by kmorcinek** [m-m-c-c/blef#10]
Now the Card is a simple enum
`public enum Card
{
    Nine,
    Ten,
    Jack,
    Queen,
    King,
    Ace
}`

and it lacks color. However color is important only for the best PokerHands, so better leave the enum now for simplicity. What do you think?

**Comment by ArturWincenciak** [comment]
Card must have pair of value: one of enum SUIT { Diamonds, Hearts, Clubs, Spades } with one enum Card { Nine, Ten, Jack, Queen, King, Ace }

**Comment by ArturWincenciak** [comment]
public enum Card { Nine, Ten, Jack, Queen, King, Ace } should names Rank

**Comment by ArturWincenciak** [comment]
Class Card should have Suit and Rank property.
