### ISSUE TITLE
Zgodzenie się na klasy którę będą API do komunikacji między wszystkimi komponentami

### ISSUE THREAD

**Issue by kmorcinek** [m-m-c-c/blef#12]
Jeśliby szybko powstały klasy, dzięki którym możemy przekazać dane służące do komunikacji to równolegle mogłaby już powstawać 3 dużę rzeczy:
  - metoda na kliencie będzie wyglądać "PokerHand BetHand(GameHistory gameHistory)" i metody do rejestracji klienta w serwerze, kończenie gdy i ogłaszanie wyników
  - logika serwera odpowiedzialna za sprawdzanie kto wygrał przegrał i granie dalej
  - logika klienta odpowiedzialna za wybieranie kolejnego ruchu.

`class GameHistory
{
    PlayerBet[] PlayerBets;
    Table Table;
}

class PlayerBet
{
    Player Player;
    PokerHand Hand;
}

abstract class PokerHand
{
    // derived classes has logic
}

class Table
{
    PlayerHand[] PlayerHands;
}

class PlayerHand
{
    Card[] Cards;
    Player Player;
}

class Player
{
    string Name;
}`

**Comment by Enumix** [comment]
Klient nie może dostać w GameHistory obiektu Table 😃 Myślę, że wystarczy mu historia typów wszystkich graczy. 
Nie uwzględniono tu możliwości sprawdzenia, nie bardzo widzę to w modelu w którym metoda klienta zwraca PlayerHand, może lepiej zwracać coś w stylu PlayerMove:

enum PlayerChoice (albo lepsza nazwa, to pierwsze skojarzenie)
{
Unknown,
Check,
Bet
}

class PlayerMove 
{
public PlayerChoice Choice {get;}
public PokerHand PokerHand {get;}

public PlayerMove(PokerHand pokerHand)
{
Choice = PlayerChoice.Bet;
PokerHand = pokerHand;
}

public PlayerMove()
{
Choice = PlayerChoice.Check;
}
}

**Comment by cezarypiatek** [comment]
Klient nie powinien dostawać historii ruchów tylko ostatnio obstawiony układ. Historię powinien sobie śledzić sam, na tym polega cała trudność podczas gry w realu ;)

**Comment by kmorcinek** [comment]
PlayerChoice i PlayerMove +1

**Comment by kmorcinek** [comment]
> Klient nie powinien dostawać historii ruchów tylko ostatnio obstawiony układ. Historię powinien sobie śledzić sam, na tym polega cała trudność podczas gry w realu ;)

Myślałem że to już w busie przegadaliśmy. Dla prostoty przesyłamy całą historię, jest wszystko bezstanowe. Po co mamy budować logike która będzie składać wszystko z poprzednich requestów i trzymać stan skoro możemy tego nie robić. Piszemy MVP.

**Comment by cezarypiatek** [comment]
Czyli klient obstawiając kolejny układ wysyłałby historię + nowy układ?

**Comment by kmorcinek** [comment]
tylko nowy układ
