### ISSUE TITLE
Bug: KKQQ is greater than AA99 (TwoPair comparision)

### ISSUE THREAD

**Issue by kmorcinek** [m-m-c-c/blef#25]
Look at the failing test _TwoPair_Ace_and_Nine_should_be_stronger_than_king_and_queen_

@cezarypiatek please rename the test if see better name.

**Comment by cezarypiatek** [comment]
Thanks for your attentions. I had a bug in code that generate test data and I missed this test case. I'm working on it.

**Comment by cezarypiatek** [comment]
@kmorcinek prośba o weryfikację poprawki

**Comment by kmorcinek** [comment]
zweryfikowane, ale tak jak opisałem w #23, ten test #25 powinien być explicit. Do teraz myślałem że test zginął.
